morph-l2/morph

ops/docker/Dockerfile.l1-beacon
ops/docker/docker-compose-4nodes.yml

upgrade prysm to v4.2.1 so that the ethereum validator can correctly verify the kzg commitment by the updated setup

upgrade prysm to v4.2.1 

---

contracts/contracts/L1/rollup/IRollup.sol
contracts/contracts/L1/rollup/Rollup.sol
contracts/contracts/L1/staking/IL1Sequencer.sol
contracts/contracts/L1/staking/IStaking.sol
contracts/contracts/L1/staking/L1Sequencer.sol
contracts/contracts/L1/staking/Staking.sol
contracts/contracts/test/L1Sequencer.t.sol
contracts/contracts/test/Rollup.t.sol
contracts/contracts/test/base/L1MessageBase.t.sol

Before BLS is implemented, the accuracy of the sequencer set uploaded by rollup cannot be guaranteed.
But the submitter is required to be in the sequencer set which version it submitted.
Therefore, if the batch is successfully challenged, only the submitter will be punished.

Audit N7: Fix slash

---

node/core/batch.go
node/core/executor.go
node/db/keys.go
node/sync/deposit_log.go
node/types/types.go
tx-submitter/cmd/main.go
tx-submitter/entry.go
tx-submitter/services/rollup.go
tx-submitter/services/utils.go

declaration redundancy

---

node/types/chunk.go

change to not use reserved words for variables

---

contracts/contracts/L1/staking/Staking.sol
contracts/contracts/test/base/L1MessageBase.t.sol
contracts/deploy/018-StakingInit.ts

Issue: When a challenge ends in the Rollup contract with the challenger winning, the staking.slash function is invoked. However, the staking.slash function includes the onlySequencerContract modifier, which should be changed to onlyRollupContract here.
Solution: Update the modifier to allow Rollup contract to call slash function.

OZ  Audit N1 : Fix batch challenge

---

contracts/contracts/L1/rollup/Rollup.sol

Issue: During the validity check of finalizeBatch for batches, it doesn't verify whether the batch has been successfully challenged. This could result in a batch that has already been successfully challenged being finalized, leading to malicious withdrawals.
Fix: Add the attribute challengeSuccess to the BatchChallenge structure. Set its value to true when a batch is successfully challenged to indicate that the batch has been successfully challenged. Add the `batchChallengedSuccess` function for querying the result of batch challenges. Use the `batchChallengedSuccess` function during the finalizeBatch process to check if the batch has been successfully challenged.

OZ Audit N2 : Check challenge results

---

contracts/contracts/L1/rollup/Rollup.sol

Issue: After a batch is reverted, only its batchHash is set to bytes32(0). However, the batchExist check only examines the originTimestamp, which causes the reverted batch to be considered as an existing batch. leading to malicious withdrawals.
Fix: Update the batchExist function to check filter out batches that have been reverted.

OZ Audit N3: Batch exist check

---

gas-oracle/app/src/gas_price_oracle.rs
gas-oracle/app/src/overhead/blob_client.rs
gas-oracle/app/src/overhead/calculate.rs
gas-oracle/app/src/overhead/error.rs
gas-oracle/app/src/overhead/overhead.rs

1. transaction `blobVersionedHashes`
2. transactionReceipt `blobGasPrice`
3. block `parent_beacon_block_root`, `excess_blob_gas`
The fields mentioned above are all supported by ethers's Transaction, so replace ExecutionNode.

feat(gas-oracle): use ethers's provider instead of ExecutionNode

---

node/core/batch.go

We forget setting `postStateRoot` and `withdrawRoot`  when initializing `batchingCache` in `calculateCapWithProposalBlock`, making the batch lost these two values if the current block is a new batchPoint. 
This PR adds `postStateRoot` and `withdrawRoot`  to fix this issue.

Add postStateRoot and withdrawRoot when rebuilding batch cache

---

contracts/contracts/l1/rollup/Rollup.sol

An unchecked batch reversion will cause challenge invalidation for any committed batch, leading to batch rollback issues for challengers, as the isChallenged flag will reset unexpectedly.

Audit: Revert batch check batch in challenge

---

contracts/contracts/l1/gateways/L1ReverseCustomGateway.sol

`L1ReverseGateway` cannot transfer token to receiver when user call `onDropMessage`,  use mint instead.

Audit: L1ReverseGateway mint token when drop message

---

node/db/store.go
node/derivation/batch_info.go
node/derivation/database.go
node/derivation/derivation.go

Fix start height of derivation

Fix start height of derivation

---

tx-submitter/metrics/metrics.go
tx-submitter/services/rollup.go
tx-submitter/services/utils.go

- Add couter metrics for finalize, rollup and l1CollectFee to track Rollup cost & batch income
- Add batchCache for use in other functions of the rollup service.

Submitter adjust metrics

---

contracts/contracts/l1/rollup/Rollup.sol
contracts/contracts/test/Rollup.t.sol

Check previous state root on `SubmitBatch`.
Because the prevStateRoot is not validated until a batch is finalized, a committed batch with a malicious prevStateRoot can be used to both (a) win challenges against honest challengers and (b) halt the chain since it will be approved but be unable to be finalized.

Check previous state root

---

contracts/contracts/l1/rollup/MultipleVersionRollupVerifier.sol
contracts/contracts/l1/rollup/Rollup.sol
contracts/contracts/test/MultipleVersionRollupVerifier.t.sol

revert if `verifier not found`

Revert ErrorVerifierNotFound

---

tx-submitter/services/utils.go

- Fixed blob fee calculation logic in Blob transaction type
- Added judgment for weiAmt being nil to avoid potential null pointer exceptions

Fix transaction fee calculation issue

---

tx-submitter/entry.go
tx-submitter/flags/flags.go
tx-submitter/l1checker/blockmonitor.go
tx-submitter/l1checker/blockmonitor_test.go
tx-submitter/services/rollup.go
tx-submitter/utils/config.go

* Add BlockMonitor struct to monitor L1 block growth
* Integrate BlockMonitor into the Rollup struct to perform L1 health checks
* Add CLI flag and configuration option to set the block growth threshold
* Implemente related test cases to validate the block growth monitoring feature

feat(tx-submitter): Add L1 Block Growth Monitoring Feature

---

tx-submitter/db/db.go
tx-submitter/entry.go
tx-submitter/event/indexer.go
tx-submitter/event/storage.go
tx-submitter/event/storage_test.go
tx-submitter/params/leveldb_keys.go
tx-submitter/services/rollup.go
tx-submitter/services/rotator.go

- Remove EventInfoStorage file operations
- Use Db from tx-submitter/db for event info storage
- Update EventIndexer to use EventInfoStorage interface
- Modify Rollup and Rotator to use new EventInfoStorage implementation
- Add GetString and PutString methods to db.Db
- Create EventInfoKey constant in params

feat(event): replace file storage with leveldb for event info

---

tx-submitter/entry.go
tx-submitter/flags/flags.go
tx-submitter/mock/l1mock.go
tx-submitter/services/rollup.go
tx-submitter/services/rollup_test.go
tx-submitter/utils/config.go

Enhancements to tx-submitter Fee Handling, Logging, and Testing
Feature Improvements:
- Added detailed logging for market fee information, including base fee and tip, as well as configurations for new fee-related parameters.
Introduced logging updates after tip bump calculations and blob fee adjustments.
Testing Enhancements:
- Added a mock L1 client for testing and enhanced Rollup service tests to cover more scenarios.
Implemented new test cases for GetGasTipAndCap and ReSubmitTx functionalities, improving error handling and edge case coverage.
Refactor:
- Updated tip fee handling by increasing the default TipFeeBump from 100% to 120%.
Simplified tip calculation by moving minimum tip enforcement logic from GetGasTipAndCap to ReSubmitTx.
Fee Configuration Changes:
- Removed …

feat(tx-submitter): add tip fee bump functionality

---

contracts/contracts/l2/staking/L2Staking.sol

I've found a potential security vulnerability in the L2Staking contract's _transfer and _transferFrom functions:
The issue is in both transfer functions where they check the balance difference after the transfer. While they verify that the balance increased by the expected amount, they don't check if the initial transfer operation was successful.
This commit adds explicit checks for the return values of ERC20 transfer and transferFrom operations in the L2Staking contract. While the contract already verified balance changes, it didn't check if the initial transfer succeeded.
- Add require statement to check transfer() return value
- Add require statement to check transferFrom() return value
- Improve error messages to be more specific
- Maintain existing balance difference checks as …

fix: Add return value checks for ERC20 transfers in L2Staking

---

contracts/contracts/test/L2Staking.t.sol
contracts/tasks/staking_upgrade.ts
node/core/executor.go
oracle/oracle/rollup.go

1. **`L2Staking.t.sol`**:
- Corrected "sequncer" to "sequencer" in comments describing test scenarios.
2. **`staking_upgrade.ts`**:
- Fixed "implemention" to "implementation" in a log message.
3. **`executor.go`**:
- Corrected "alllowed" to "allowed" in error messages.
4. **`rollup.go`**:
- Fixed "gernerate" to "generate" in an error message.

Fix typos in `rollup.go`, `executor.go`, `staking_upgrade.ts`, and `L2Staking.t.sol`

---

contracts/tasks/overflow_test.ts
oracle/oracle/oracle.go
oracle/oracle/reward.go

- Corrected **recipt → receipt** in `overflow_test.ts`.  
- Fixed **stoped → stopped** in `oracle.go`.  
- Corrected **falied → failed** in `reward.go`.

Fix spelling error

---

tx-submitter/services/rollup.go

Fix the err caused by missing chainid when resubmitting the finalize tx

Add ChainID to DynamicFeeTx constructor

---

tx-submitter/entry.go
tx-submitter/flags/flags.go
tx-submitter/iface/rollup.go
tx-submitter/services/rollup.go
tx-submitter/services/rollup_handle_test.go
tx-submitter/services/rotator.go
tx-submitter/utils/config.go

- Replaces L2Gov contract-based epoch retrieval with a configurable RollupEpoch parameter.
- Removes associated flags, methods, and logic tied to L2Gov contract.

feat: remove L2Gov contract dependency
